03.09.2022 19:44:44 | Database.__init__
03.09.2022 19:44:45 | Database.connect
	2022-09-03 19:44:45,003 INFO sqlalchemy.engine.Engine BEGIN (implicit)
	2022-09-03 19:44:45,004 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("User")
	2022-09-03 19:44:45,004 INFO sqlalchemy.engine.Engine [raw sql] ()
	2022-09-03 19:44:45,004 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Category")
	2022-09-03 19:44:45,004 INFO sqlalchemy.engine.Engine [raw sql] ()
	2022-09-03 19:44:45,004 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Item")
	2022-09-03 19:44:45,004 INFO sqlalchemy.engine.Engine [raw sql] ()
	2022-09-03 19:44:45,005 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("Field")
	2022-09-03 19:44:45,005 INFO sqlalchemy.engine.Engine [raw sql] ()
	2022-09-03 19:44:45,005 INFO sqlalchemy.engine.Engine COMMIT
03.09.2022 19:45:21 | Database.__init__
03.09.2022 19:45:21 | Database.connect
	(sqlite3.OperationalError) unable to open database file
	(Background on this error at: https://sqlalche.me/e/14/e3q8)
03.09.2022 19:46:05 | Database.disconnect
	'NoneType' object has no attribute 'close'